ModalBottomSheet 적용
crucial-sub/odot pull request #2
Opened 2024-03-19 09:45 UTC by crucial-sub

modal 바텀시트 구현
todo 추가를 Stack Navigation 이동 없이 바텀시트안에서 바로 할 수 있도록 구현
children을 props로 받아 내부 contents만 바꾸면 재사용 가능하도록 구현

2024-03-19 13:12 UTC, hoonjoo-park requested changes

2024-03-19 13:12 UTC, hoonjoo-park commented on src/App.tsx
>  RecoilEnv.RECOIL_DUPLICATE_ATOM_KEY_CHECKING_ENABLED = false;
이거는 왜 false로 제거한 것인지?

2024-03-19 13:12 UTC, hoonjoo-park commented on src/components/BottomSheet/ModalBottomSheet.tsx
> +const ModalBottomSheet = ({children}: any) => {
any 사용은 지양 부탁드립니다

2024-03-19 13:12 UTC, hoonjoo-park commented on src/components/BottomSheet/ModalBottomSheet.tsx
> +  const [isVisible, setIsVisible] = React.useState(visibleState);
isGlobalVisible 또는 isVisibleRecoilState 등으로 하는게 더 가독성이 좋을 것 같습니다.

2024-03-19 13:12 UTC, hoonjoo-park commented on src/components/BottomSheet/ModalBottomSheet.tsx
> +  });
useEffect, 함수, 객체 등은 개행을 해주는 것이 가독성 측면에서 좋습니다.

2024-03-19 13:12 UTC, hoonjoo-park commented on src/components/NewTask/NewTaskButton.tsx
이걸 커스텀 훅을 만들어 사용하면 좋을 것 같아요. 
ex) const { showBottomSheet, hideBottomSheet } = useBottomSheet()

2024-03-19 13:12 UTC, hoonjoo-park commented on src/components/NewTask/NewTaskInput.tsx
> +  },
개인적으로는 이미 이 컴포넌트 자체가 NewTaskInput이기 때문에
그냥 wrapper로 네이밍 해도 되지 않을까 싶긴 합니다.

2024-03-19 13:12 UTC, hoonjoo-park commented on src/components/NewTask/NewTaskButton.tsx
>  const NewTaskButton = () => {
prop을 받지 않는 컴포넌트네요
이런 경우는 React.memo를 사용해서 최적화 하는게 더 좋지 않을까요?

2024-03-19 13:12 UTC, hoonjoo-park commented on src/components/NewTask/NewTaskModalContents.tsx
> +const NewTaskModalContents = () => {
마찬가지입니다

2024-03-19 13:12 UTC, hoonjoo-park commented on src/recoil/index.ts
> +  default: false,
key는 현업에서 camelCase보다는 kebab-case의 사용을 많이 하더라고요.

2024-03-19 13:12 UTC, hoonjoo-park commented on src/screens/TodoListScreen.tsx
> +      </ModalBottomSheet>
이렇게 구조를 짜면,
`bottomsheet`를 사용해야 하는 컴포넌트들은 모두 이런식으로 컴포넌트 내에 바텀시트를 생성해 줘야 되지 않을까요?

그렇게 된다면, 번들 크기도 늘어나고, 유지보수성도 떨어지며, 개발 효율성도 떨어질 것 같습니다.

위에서 말했던 useBottomSheet를 만들고, 
이 커스텀 훅으로 어디서든 바텀시트를 열고 닫을 수 있는 로직을 한번 고민해 보세요!

2024-03-19 13:12 UTC, hoonjoo-park commented on src/screens/TodoListScreen.tsx
> +      </ModalBottomSheet>
즉, 바텀시트를 사용하고자 하는 스크린에서는
useBottomSheet 훅만 사용해서 바텀시트를 열 수 있어야 하는 것이 핵심인 것 같습니다.

2024-03-19 16:04 UTC, crucial-sub commented on src/App.tsx
>  RecoilEnv.RECOIL_DUPLICATE_ATOM_KEY_CHECKING_ENABLED = false;
Duplicate atom key 관련 오류가 뜨길래 설정해놨었는데 다시 지워도 될것같네요

2024-03-20 02:04 UTC, hoonjoo-park requested changes

2024-03-20 02:04 UTC, hoonjoo-park commented on src/components/BottomSheet/ModalBottomSheet.tsx
> +  const {hideBottomSheet} = useBottomSheet();
음 useBottomSheet 내에 isGlobalVisible, content 등의 atom들을 넣고, 반환해 주면
유지보수성이 올라가고, 개발하는 입장에서 더 편하지 않을까요?

2024-03-20 02:04 UTC, hoonjoo-park commented on src/components/NewTask/NewTaskButton.tsx
> +    showBottomSheet(<NewTaskModalContents />);
이런 경우는, 인자 열거형 보다는 객체로 보내는 것이 더 가독성이 좋고, 실수할 확률도 줄어듭니다.

ex) showBottomSheet({ content: SomeComponent, props: { ... } })

2024-03-21 11:10 UTC, merged